apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: mysql-vm-lb-tp2i
  namespace: cd-demo
spec:
  selector:
    mysql-vm-lb-tp2i: vm-lb-selector
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306