apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vm-pvc-0
  labels:
    vm-selector: mysql-vm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-storage-policy
