apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vm1-pvc-0
  namespace: namespace-1
  labels:
    vm-selector: mysql-vm1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-storage-policy