apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vks-01
  namespace: namespace-1
  labels:
    tkg-cluster-selector: vks-01
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.2.0
    version: v1.31.1---vmware.2-fips-vkr.2
    variables:
      - name: vmClass
        value: best-effort-xsmall
      - name: storageClass
        value: k8s-storage-policy
    controlPlane:
      replicas: 3
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon
    workers:
      machineDeployments:
        - class: node-pool
          name: tkg-cluster-nodepool-8308
          replicas: 1
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=photon